### PR TITLE
Fixes for streams and IJulia

### PR DESCRIPTION
**Pull request by timholy**
These fixes are thanks to @Evizero for his careful testing in https://github.com/timholy/Images.jl/pull/445.

### CODE REVIEW

**Comment by Evizero** [comment]
You may need to bump the FileIO version in REQUIRE

**Comment by timholy** [comment]
Good thinking. Done.

**Comment by Evizero** [comment]
curious error. I'll boot my mac up again and take a look

**Comment by timholy** [comment]
I may have fixed it. But certainly any tests you can do might be faster than Travis.

**Comment by Evizero** [comment]
```
Out of 75 total facts:
  Verified: 72
  Pending:  3
  > Streams
    > saving
    > loading
ERROR: LoadError: FactCheck finished with 2 non-successful tests.
 in error at /usr/local/Cellar/julia/0.4.3/lib/julia/sys.dylib
 in exitstatus at /Users/csto/.julia/v0.4/FactCheck/src/FactCheck.jl:563
 in include at /usr/local/Cellar/julia/0.4.3/lib/julia/sys.dylib
 in include_from_node1 at /usr/local/Cellar/julia/0.4.3/lib/julia/sys.dylib
 in process_options at /usr/local/Cellar/julia/0.4.3/lib/julia/sys.
```

**Comment by timholy** [comment]
Hmm, no sign of which tests failed?

**Comment by Evizero** [comment]
not to me. here is more output

```
S X reader
  > Autumn leaves
  > Camerman
Feb 28 01:09:52  julia[9718] <Info>: ImageIO: _TIFFVSetField tiff data provider: Null count for "Tag 34022" (type 1, writecount -3, passcount 1)
Feb 28 01:09:52  julia[9718] <Notice>: 
Feb 28 01:09:52  julia[9718] <Info>: ImageIO: _TIFFVSetField tiff data provider: Null count for "Tag 34025" (type 1, writecount -3, passcount 1)
Feb 28 01:09:52  julia[9718] <Notice>: 
Feb 28 01:09:52  julia[9718] <Info>: ImageIO: _TIFFVSetField tiff data provider: Null count for "Tag 34026" (type 1, writecount -3, passcount 1)
Feb 28 01:09:52  julia[9718] <Notice>: 
Feb 28 01:09:52  julia[9718] <Info>: ImageIO: _TIFFVSetField tiff data provider: Null count for "Tag 34022" (type 1, writecount -3, passcount 1)
Feb 28 01:09:52  julia[9718] <Notice>: 
Feb 28 01:09:52  julia[9718] <Info>: ImageIO: _TIFFVSetField tiff data provider: Null count for "Tag 34025" (type 1, writecount -3, passcount 1)
Feb 28 01:09:52  julia[9718] <Notice>: 
Feb 28 01:09:52  julia[9718] <Info>: ImageIO: _TIFFVSetField tiff data provider: Null count for "Tag 34026" (type 1, writecount -3, passcount 1)
Feb 28 01:09:52  julia[9718] <Notice>: 
  > Earth Apollo
  > Fabio
  > House
Feb 28 01:09:55  julia[9718] <Info>: ImageIO: _TIFFVSetField tiff data provider: Null count for "Tag 34022" (type 1, writecount -3, passcount 1)
Feb 28 01:09:55  julia[9718] <Notice>: 
Feb 28 01:09:55  julia[9718] <Info>: ImageIO: _TIFFVSetField tiff data provider: Null count for "Tag 34025" (type 1, writecount -3, passcount 1)
Feb 28 01:09:55  julia[9718] <Notice>: 
Feb 28 01:09:55  julia[9718] <Info>: ImageIO: _TIFFVSetField tiff data provider: Null count for "Tag 34026" (type 1, writecount -3, passcount 1)
Feb 28 01:09:55  julia[9718] <Notice>: 
Feb 28 01:09:55  julia[9718] <Info>: ImageIO: _TIFFVSetField tiff data provider: Null count for "Tag 34022" (type 1, writecount -3, passcount 1)
Feb 28 01:09:55  julia[9718] <Notice>: 
Feb 28 01:09:55  julia[9718] <Info>: ImageIO: _TIFFVSetField tiff data provider: Null count for "Tag 34025" (type 1, writecount -3, passcount 1)
Feb 28 01:09:55  julia[9718] <Notice>: 
Feb 28 01:09:55  julia[9718] <Info>: ImageIO: _TIFFVSetField tiff data provider: Null count for "Tag 34026" (type 1, writecount -3, passcount 1)
Feb 28 01:09:55  julia[9718] <Notice>: 
  > Jetplane
Feb 28 01:09:56  julia[9718] <Info>: ImageIO: _TIFFVSetField tiff data provider: Null count for "Tag 34022" (type 1, writecount -3, passcount 1)
Feb 28 01:09:56  julia[9718] <Notice>: 
Feb 28 01:09:56  julia[9718] <Info>: ImageIO: _TIFFVSetField tiff data provider: Null count for "Tag 34025" (type 1, writecount -3, passcount 1)
Feb 28 01:09:56  julia[9718] <Notice>: 
Feb 28 01:09:56  julia[9718] <Info>: ImageIO: _TIFFVSetField tiff data provider: Null count for "Tag 34026" (type 1, writecount -3, passcount 1)
Feb 28 01:09:56  julia[9718] <Notice>: 
Feb 28 01:09:56  julia[9718] <Info>: ImageIO: _TIFFVSetField tiff data provider: Null count for "Tag 34022" (type 1, writecount -3, passcount 1)
Feb 28 01:09:56  julia[9718] <Notice>: 
Feb 28 01:09:56  julia[9718] <Info>: ImageIO: _TIFFVSetField tiff data provider: Null count for "Tag 34025" (type 1, writecount -3, passcount 1)
Feb 28 01:09:56  julia[9718] <Notice>: 
Feb 28 01:09:56  julia[9718] <Info>: ImageIO: _TIFFVSetField tiff data provider: Null count for "Tag 34026" (type 1, writecount -3, passcount 1)
Feb 28 01:09:56  julia[9718] <Notice>: 
  > Lighthouse
  > Mandrill
  > Moonsurface
  > Mountainstream
  > MRI Stack
  > M51
  > HeLa cells
  > Blobs GIF
  > Multichannel timeseries OME
Out of 75 total facts:
  Verified: 72
  Pending:  3
  > Streams
    > saving
    > loading
ERROR: LoadError: FactCheck finished with 2 non-successful tests.
 in error at /usr/local/Cellar/julia/0.4.3/lib/julia/sys.dylib
 in exitstatus at /Users/csto/.julia/v0.4/FactCheck/src/FactCheck.jl:563
 in include at /usr/local/Cellar/julia/0.4.3/lib/julia/sys.dylib
 in include_from_node1 at /usr/local/Cellar/julia/0.4.3/lib/julia/sys.dylib
 in process_options at /usr/local/Cellar/julia/0.4.3/lib/julia/sys.dylib
 in _start at /usr/local/Cellar/julia/0.4.3/lib/julia/sys.dylib
while loading /Users/csto/.julia/v0.4/QuartzImageIO/test/runtests.jl, in expression starting on line 215
======================================[ ERROR: QuartzImageIO ]======================================

```

**Comment by timholy** [comment]
OK, I think I was using FactCheck improperly, maybe try again?

**Comment by Evizero** [comment]
```
Streams
  > saving
    Failure :: (line:505) :: saving :: fact was false
      Expression: imgcmp --> img
        Expected: RGB4 Images.Image with:
  data: 768x512 Array{ColorTypes.RGB4{FixedPointNumbers.UFixed{UInt8,8}},2}
  properties:
    imagedescription: <suppressed>
    spatialorder:  x y
    pixelspacing:  1 1
        Occurred: RGBA Images.Image with:
  data: 768x512 Array{ColorTypes.RGBA{FixedPointNumbers.UFixed{UInt8,8}},2}
  properties:
    imagedescription: <suppressed>
    spatialorder:  x y
    pixelspacing:  1 1
  > loading
    Failure :: (line:505) :: loading :: fact was false
      Expression: imgcmp --> img
        Expected: RGB4 Images.Image with:
  data: 768x512 Array{ColorTypes.RGB4{FixedPointNumbers.UFixed{UInt8,8}},2}
  properties:
    imagedescription: <suppressed>
    spatialorder:  x y
    pixelspacing:  1 1
        Occurred: RGBA Images.Image with:
  data: 768x512 Array{ColorTypes.RGBA{FixedPointNumbers.UFixed{UInt8,8}},2}
  properties:
    imagedescription: <suppressed>
    spatialorder:  x y
    pixelspacing:  1 1
Out of 2 total facts:
  Failed:   2
ERROR: LoadError: FactC
```

**Comment by Evizero** [comment]
So I added a show in line 205 to compare the content (I don't know if this helps), but here is the result

```
find(raw(imgcmp) .!= raw(img)) = Int64[]
```

**Comment by timholy** [comment]
It's coming back as an RGBA instead of RGB4. I cast it to an RGB4 just hoping to get the test to pass, but eventually we don't want to need that.

**Comment by Evizero** [comment]
```
INFO: QuartzImageIO tests passed
```

:tada:

**Comment by timholy** [comment]
Yay! Thanks yet again.

I'll squash some and merge. I won't fix the RGBA thing, but I'll file an issue that the last commit should eventually be reverted.

**Pull request merged**
