### PR TITLE
Expand the README

### PR DESCRIPTION
**Pull request by timholy**
The package could probably use a new tagged release, to make the new saving functionality available.

### CODE REVIEW

**Comment by cstjean** [comment]
It would be nice to merge/get feedback on #13 or at the very least fix the memory leak in some other way before tagging...

**Comment by timholy** [comment]
Good point. I'm not the best person to review it, unfortunately. @rsrock?

**Comment by rsrock** [comment]
Thanks for this!

**Comment by rsrock** [comment]
Will get something tagged soon, btw

**Pull request merged**
